services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'




  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-account:3306/bankacustomer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret



    depends_on:
     - broker
     - discovery-service

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-account:3306/bankaccount?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret


    depends_on:
      - customer-service
      - discovery-service
      - broker
      - mysql-account


  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka


    depends_on:
      - discovery-service


  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


  broker:
      image: confluentinc/cp-kafka:7.3.0
      container_name: broker
      ports:

        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ################

    ################
  mysql-account:
    image: mysql:5.7
    container_name: mysql-account
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: bankaccount
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret

    volumes:
      - ./mysql-account:/data/mysql

    restart: unless-stopped

  mysql-customer:
    image: mysql:5.7
    container_name: mysql-customer
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: bankcustomer
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret

    volumes:
      - ./mysql-account:/data/mysql

    restart: unless-stopped


  phpmyadmin-account:
    depends_on:
      - mysql-account
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8084:80'
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: bankaccount
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret

